version: '3'

services:
  web:
    container_name: web_container
    build: django_news
    command: bash -c "python manage.py makemigrations &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
    - ./django_news/:/app
    ports:
    - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db_contain
    image: postgres:12
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
    ports:
    - 80:80

volumes:
  postgres_data: